import { getResendClient, getFromEmail } from './resend-client'
import { generateInvoicePDF } from '@/lib/pdf/invoice-generator'
import type { InvoiceData } from '@/lib/pdf/invoice-generator'

export async function sendInvoiceEmail(invoiceData: InvoiceData): Promise<void> {
  const resend = getResendClient()
  const fromEmail = getFromEmail()

  // Generate PDF
  const pdfBuffer = await generateInvoicePDF(invoiceData)

  // Convert Uint8Array to base64 for email attachment
  const base64Pdf = Buffer.from(pdfBuffer).toString('base64')

  const emailHtml = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            background-color: #4f46e5;
            color: white;
            padding: 20px;
            border-radius: 8px 8px 0 0;
          }
          .content {
            background-color: #f9fafb;
            padding: 30px;
            border: 1px solid #e5e7eb;
          }
          .footer {
            background-color: #f3f4f6;
            padding: 20px;
            text-align: center;
            font-size: 12px;
            color: #6b7280;
            border-radius: 0 0 8px 8px;
          }
          .invoice-details {
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
          }
          .total {
            font-size: 24px;
            font-weight: bold;
            color: #4f46e5;
            margin-top: 20px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Your Order Invoice</h1>
        </div>
        <div class="content">
          <p>Hi ${invoiceData.userName},</p>
          <p>Thank you for your order! Your invoice is attached to this email.</p>
          
          <div class="invoice-details">
            <p><strong>Order ID:</strong> ${invoiceData.orderId.slice(0, 8).toUpperCase()}</p>
            ${invoiceData.restaurantName ? `<p><strong>Restaurant:</strong> ${invoiceData.restaurantName}</p>` : ''}
            <p><strong>Subtotal:</strong> $${invoiceData.subtotal.toFixed(2)}</p>
            <p><strong>Tax:</strong> $${invoiceData.taxAmount.toFixed(2)}</p>
            <p><strong>Tip:</strong> $${invoiceData.tipAmount.toFixed(2)}</p>
            <p class="total">Total: $${invoiceData.totalAmount.toFixed(2)}</p>
          </div>

          ${invoiceData.deliveryEta ? `<p><strong>Estimated Delivery:</strong> ${new Date(invoiceData.deliveryEta).toLocaleString()}</p>` : ''}
        </div>
        <div class="footer">
          <p>This invoice was automatically generated by Group Ordering.</p>
        </div>
      </body>
    </html>
  `

  try {
    const { error } = await resend.emails.send({
      from: fromEmail,
      to: invoiceData.userEmail,
      subject: `Invoice for Order #${invoiceData.orderId.slice(0, 8).toUpperCase()}`,
      html: emailHtml,
      attachments: [
        {
          filename: `invoice-${invoiceData.orderId.slice(0, 8)}.pdf`,
          content: base64Pdf,
        },
      ],
    })

    if (error) {
      throw new Error(`Failed to send email: ${error.message}`)
    }
  } catch (error) {
    console.error('Error sending invoice email:', error)
    throw error
  }
}
